server:
  port: 7000

spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:9001
      name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

