server:
  port: 7000

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:9001
  cloud:
    config:
      uri: http://localhost:9001
      name: gateway-service
      enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**

        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


